[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"

opacity = 0.9
blur = false

[font]
size = 14
normal = { family = "Hack Nerd font Mono", style = "Regular" }

[selection]
save_to_clipboard = true

[cursor]
style.blinking = "Always"
blink_interval = 500
